INSERT INTO TODO(ID, USERNAME, DESCRIPTION, DATE, DONE)
VALUES(101, 'Sagar', 'LEARN SPRING BOOT', CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, DATE, DONE)
VALUES(102, 'Sagar', 'LEARN Docker', CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, DATE, DONE)
VALUES(103, 'Sagar', 'LEARN Kubernetes', CURRENT_DATE(), false);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, DATE, DONE)
VALUES(104, 'Sagar', 'LEARN Frontend Development', CURRENT_DATE(), false);